FROM node:18-alpine as base
RUN apk add --no-cache libc6-compat
WORKDIR /client
COPY package*.json ./
EXPOSE 3000

FROM base as dev
ENV NODE_ENV=development
RUN npm install 

COPY . .

CMD npm run dev