version: "3.8"
services:
  client:
    build:
      context: ./client
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
      - /client/node_modules
      - /client/.next
    ports:
      - "3000:3000"
    networks:
      - coopers-epeixoto
    restart: "on-failure"

  server:
    build:
      context: ./server
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "4001:4001"
    networks:
      - coopers-epeixoto
    restart: "on-failure"

  nginx:
    build: ./nginx
    ports:
      - 80:80
    networks:
      - coopers-epeixoto
    restart: "on-failure"
    depends_on:
      - client

networks:
  coopers-epeixoto:
    driver: bridge
