import localFont from "next/font/local";
import "./globals.css";

import { cookies } from "next/headers";

import jwt from "jsonwebtoken";
import { UserProvider } from "./userContext";
import { JWT_SECRET } from "@/constants/secrets";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let decoded;
  const token = cookies().get("coopers-session")?.value;

  if (token) {
    decoded = jwt.verify(token, JWT_SECRET);
  }

  return (
    <html lang="en">
      <UserProvider userData={decoded?.user}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
